{% set version = "1.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-commonmark
  version: {{ version|replace("-", "_") }}

source:
  fn: commonmark_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/commonmark_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/commonmark/commonmark_{{ version }}.tar.gz
  sha256: 7fa81635bf0d26395fdd8dd830e16f9910a388faa949b2874aed7a505f2e9dcb

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('commonmark')"  # [not win]
    - "\"%R%\" -e \"library('commonmark')\""  # [win]

about:
  home: https://github.com/jeroenooms/commonmark http://commonmark.org/help/
  license: BSD_2_clause
  summary: The CommonMark specification defines a rationalized version of markdown syntax. This
    package uses the 'cmark' reference implementation for converting markdown text into
    various formats including html, latex and groff man. In addition it exposes the
    markdown parse tree in xml format. The latest version of this package also adds
    support for Github extensions including tables, autolinks and strikethrough text.
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
