{% set version = "1.4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-commonmark
  version: {{ version|replace("-", "_") }}

source:
  fn: commonmark_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/commonmark_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/commonmark/commonmark_{{ version }}.tar.gz
  sha256: 865ecf9432763393ca9de52d0106a58c4be9e8d5196da60e068eed0b67ca68ed

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - libgcc               # [not win]

test:
  commands:
    - $R -e "library('commonmark')"  # [not win]
    - "\"%R%\" -e \"library('commonmark')\""  # [win]

about:
  home: https://github.com/jeroenooms/commonmark http://commonmark.org/help/
  license: BSD_2_clause
  summary: The CommonMark specification defines a rationalized version of markdown syntax. This
    package uses the 'cmark' reference implementation for converting markdown text into
    various formats including html, latex and groff man. In addition it exposes the
    markdown parse tree in xml format. The latest version of this package also adds
    support for Github extensions including tables, autolinks and strikethrough text.
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
