{% set version = '1.7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-commonmark
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/commonmark_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/commonmark/commonmark_{{ version }}.tar.gz
  sha256: d14a767a3ea9778d6165f44f980dd257423ca6043926e3cd8f664f7171f89108

build:
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('commonmark')"           # [not win]
    - "\"%R%\" -e \"library('commonmark')\""  # [win]

about:
  home: http://github.com/jeroen/commonmark (devel) https://github.github.com/gfm/ (spec)
  license: BSD_2_clause
  summary: The CommonMark specification defines a rationalized version of markdown syntax. This
    package uses the 'cmark' reference implementation for converting markdown text into
    various formats including html, latex and groff man. In addition it exposes the
    markdown parse tree in xml format. Also includes opt-in support for GFM extensions
    including tables, autolinks, and strikethrough text.
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: commonmark
# Type: Package
# Title: High Performance CommonMark and Github Markdown Rendering in R
# Version: 1.7
# Authors@R: c( person("Jeroen", "Ooms", ,"jeroen@berkeley.edu", role = c("aut", "cre")), person("John MacFarlane", role = "cph", comment = "Author of cmark"))
# URL: http://github.com/jeroen/commonmark (devel) https://github.github.com/gfm/ (spec)
# BugReports: http://github.com/jeroen/commonmark/issues
# Description: The CommonMark specification defines a rationalized version of markdown syntax. This package uses the 'cmark' reference implementation for converting markdown text into various formats including html, latex and groff man. In addition it exposes the markdown parse tree in xml format. Also includes opt-in support for GFM extensions including tables, autolinks, and strikethrough text.
# License: BSD_2_clause + file LICENSE
# Suggests: curl, testthat, xml2
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2018-12-01 11:57:14 UTC; jeroen
# Author: Jeroen Ooms [aut, cre], John MacFarlane [cph] (Author of cmark)
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2018-12-01 12:30:03 UTC
