appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: pVX/HYDhXnW2Ap5YndQvMi9V5KiH2cikNmObOGmBXM0jnGxY2ojkM+pqFCX6qlDA7daOJ592Ulqbhqh9/HVZMP4v4UdZZBUpXQIGvLDk6+UeNu1mL53R9I/a5zojEGZ9gXF+NrGkrAsnnrjwmBrKbwcGXnHZNDEm0rRTvpZmTr3hD7+BilQdTvN3ascSm8tO9siK5ruOuN/UC3pyhlEbCnNyTDvSMSM1r5r576GbxlXKSeRqKSjlirvwcdFpZqht8RtS9Wa7hoixaQACPyCwcd9h/sCrx4hffKcIQquHjvA/VNmITC/TjSxYFhD5jYX2kgUsYh8jnp+Qz77QEKHW0L+j6qbDtr/QfDpYLhc9jdypKKbvVCrogoD5qHQFVUkE4ue24KBSTRGroms1AXuw608eghPsdCZbWdexjmf5F6CSyAzY2jSqCJHXWGaABPm8MptExvaG1Y0xhEwwdKguna4eKL50y5GjQrWzL9OxbQCv64RHRsKpTMg3ulTEB75uwU42H/ZgJ4sda35jdHtb5Nvk+YWPZMbKslE9YxzXpgbFx7yQMr5gEwgd6vnHqASJRKGcun9cgyqXK9SBzYBI6EjhVsTjPeIkNR6flujQs8ZhI87pITSSnwhVW9EkyrSxUof0tFeXwtGWYY14PjS27/Bh76VhZf+ZLPx9ZBY7K48=}
